### ISSUE TITLE
Resuming survey restarts from previous question

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#1]
**WHAT** : If you don't answer and restart the skill, it will start with the previous -already answered- question and not the question you paused the skill at. 

**HOW TO REPRODUCE** : 
*Complete skill up to q_q11.
*Do not answer q_q11 
*Resume skill
*It will restart from q_q10 which was previously already answered.

**Comment by vitaliidanchul** [comment]
fixed
