### ISSUE TITLE
Pausing the survey after alexa prompts the user with answers and resuming it leads to wrong prompt

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#10]
**WHAT** 
1. Start one question
2. Answer the wrong answer (For example for the question one answer "maybe")
3. Alexa will prompt you with the possible answers.
4. Kill the survey
5. Restart the survey
6. Instead of telling you that "You have a survey started. Do you want to resume it or start a new one" it prompts the user with the possible answers for the paused question (For question one, it prompts the user "yes", "no", "maybe").

**PROPOSED FIX**
Instead, it should prompt the user with "You have a survey started. Do you want to resume it or start a new one? " If user says "resume" it should ask the paused question again instead of directly prompting the user with the answers.

**Comment by ghost** [comment]
fixed
