### ISSUE TITLE
q_8 has no answer when pausing survey 

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#3]
**WHAT** 
In the last survey answer pausing & resuming the survey around question 8 leads to no answer recorded for question 8 but survey marked as completed.
![screen shot 2018-08-17 at 9 35 52 am](https://user-images.githubusercontent.com/8838962/44278019-867ff580-a201-11e8-9250-7b6749af3743.png)

**Comment by ivan-sagal** [comment]
Have tested the survey back and forth, but could not reproduce the issue. We stopped survey at #8 unanswered, at #8 answered, etc. and when completed all questions had answers. Can you please retest.
