### ISSUE TITLE
Adding a new question to the survey and answering an answer that is unavailable leads to error

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#4]
**WHAT** Currently, adding a new question and not answering the set of answers leads to "Server took too long to respond error". Instead, it should trigger the "Re-prompt text".

**HOW** 
1. Open "heart failure" skill
2. First question is "Do you have angina?"
3. Possible answers are "YES" or "NO. Answer "I DONT KNOW".
4. Skill fails.

**Comment by ivan-sagal** [comment]
The issue here related to you adding "YES" and "NO" answers, but not enabling them - there are checkmarks on the right of each answer. We made some changes to have added answers enabled by default. Please retest.
