### ISSUE TITLE
Adding a new question doesn't save the answers

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#5]
**WHAT** For survey one, adding a new question such as question "q_14" and answering an answer from the answer set such as "YES" doesn't save the answer when exporting the CSV file.

**HOW TO REPRODUCE**
1. Open HF survey
2. Answer the first question which is q_q14 as "YES".
3. Look on admin panel -> answers to q_q14 isn't saved.

**Comment by ivan-sagal** [comment]
This relates to #4 - you added answers, but did not enable them. Please retest.
