### ISSUE TITLE
Answering an unknown answer to "q_q1" renders to Alexa repeating answers and recording two separate answers

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#6]
**WHAT** If you answer an unknown answer to "q_q1" such as "I don't know" Alexa will prompt the user the answers for the following question ("Answer 1, 2, 3 [...]) instead of prompting the user "You can say "repeat" or "start survey"). 

Additionally, if you answer that prompt it will record the answer as seen here (q_q2 = 1) then restart the survey. This shouldn't happen. 
![screen shot 2018-08-17 at 2 02 57 pm](https://user-images.githubusercontent.com/8838962/44288964-200dce00-a227-11e8-8063-48a7fa22223e.png)

*PROPOSED FIX**
1. If the user on "q_q1" answers an incorrect answer you should prompt him with this sentence "You can only say "repeat" to hear the instructions again or "start survey" to begin the questionnaire").
2. Do not record the answers to q_q1.

**Comment by ghost** [comment]
fixed
