### ISSUE TITLE
Answering something else than 'resume the survey' leads to wrong prompt

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#9]
**WHAT** Once a survey is 'paused' alexa prompts the user to 'resume survey' or 'start a new one'. Not answering either of these choices (for example saying "I don't know") leads Alexa to ask the user to answer between the different 'AnswerSets' of the paused question instead of prompting to user to say "Resume the survey" or "Start a new one".

**FIX** Instead it should ask the user to say "Resume the survey" or "Start a new one".

**Comment by ghost** [comment]
fixed
